/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_moraleboost_mecab_impl_StandardNode */

#ifndef _Included_net_moraleboost_mecab_impl_StandardNode
#define _Included_net_moraleboost_mecab_impl_StandardNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_moraleboost_mecab_impl_StandardNode
 * Method:    _surface
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_moraleboost_mecab_impl_StandardNode__1surface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_impl_StandardNode
 * Method:    _blank
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_moraleboost_mecab_impl_StandardNode__1blank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_impl_StandardNode
 * Method:    _feature
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_moraleboost_mecab_impl_StandardNode__1feature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_impl_StandardNode
 * Method:    _posid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_moraleboost_mecab_impl_StandardNode__1posid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_impl_StandardNode
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_moraleboost_mecab_impl_StandardNode__1next
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
