/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_moraleboost_mecab_Node */

#ifndef _Included_net_moraleboost_mecab_Node
#define _Included_net_moraleboost_mecab_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_moraleboost_mecab_Node
 * Method:    _surface
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_moraleboost_mecab_Node__1surface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_Node
 * Method:    _feature
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_moraleboost_mecab_Node__1feature
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_moraleboost_mecab_Node
 * Method:    _next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_moraleboost_mecab_Node__1next
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
