// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.moraleboost.mecab.impl;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ParsingRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ParsingRequest.newBuilder() to construct.
    private ParsingRequest() {}
    
    private static final ParsingRequest defaultInstance = new ParsingRequest();
    public static ParsingRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParsingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable;
    }
    
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasText) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasText()) {
        output.writeString(1, getText());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingRequest prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.moraleboost.mecab.impl.Messages.ParsingRequest.newBuilder()
      private Builder() {}
      
      net.moraleboost.mecab.impl.Messages.ParsingRequest result = new net.moraleboost.mecab.impl.Messages.ParsingRequest();
      
      @Override
      protected net.moraleboost.mecab.impl.Messages.ParsingRequest internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.moraleboost.mecab.impl.Messages.ParsingRequest();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingRequest.getDescriptor();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest getDefaultInstanceForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingRequest.getDefaultInstance();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.moraleboost.mecab.impl.Messages.ParsingRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        net.moraleboost.mecab.impl.Messages.ParsingRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingRequest) {
          return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingRequest other) {
        if (other == net.moraleboost.mecab.impl.Messages.ParsingRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setText(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string text = 1;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = "";
        return this;
      }
    }
    
    static {
      net.moraleboost.mecab.impl.Messages.getDescriptor();
    }
  }
  
  public static final class ParsingResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ParsingResponse.newBuilder() to construct.
    private ParsingResponse() {}
    
    private static final ParsingResponse defaultInstance = new ParsingResponse();
    public static ParsingResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParsingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable;
    }
    
    public static final class Morpheme extends
        com.google.protobuf.GeneratedMessage {
      // Use Morpheme.newBuilder() to construct.
      private Morpheme() {}
      
      private static final Morpheme defaultInstance = new Morpheme();
      public static Morpheme getDefaultInstance() {
        return defaultInstance;
      }
      
      public Morpheme getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor;
      }
      
      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable;
      }
      
      // required string surface = 1;
      public static final int SURFACE_FIELD_NUMBER = 1;
      private boolean hasSurface;
      private java.lang.String surface_ = "";
      public boolean hasSurface() { return hasSurface; }
      public java.lang.String getSurface() { return surface_; }
      
      // optional string blank = 2;
      public static final int BLANK_FIELD_NUMBER = 2;
      private boolean hasBlank;
      private java.lang.String blank_ = "";
      public boolean hasBlank() { return hasBlank; }
      public java.lang.String getBlank() { return blank_; }
      
      // required string feature = 3;
      public static final int FEATURE_FIELD_NUMBER = 3;
      private boolean hasFeature;
      private java.lang.String feature_ = "";
      public boolean hasFeature() { return hasFeature; }
      public java.lang.String getFeature() { return feature_; }
      
      // required uint32 posid = 4;
      public static final int POSID_FIELD_NUMBER = 4;
      private boolean hasPosid;
      private int posid_ = 0;
      public boolean hasPosid() { return hasPosid; }
      public int getPosid() { return posid_; }
      
      @Override
      public final boolean isInitialized() {
        if (!hasSurface) return false;
        if (!hasFeature) return false;
        if (!hasPosid) return false;
        return true;
      }
      
      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasSurface()) {
          output.writeString(1, getSurface());
        }
        if (hasBlank()) {
          output.writeString(2, getBlank());
        }
        if (hasFeature()) {
          output.writeString(3, getFeature());
        }
        if (hasPosid()) {
          output.writeUInt32(4, getPosid());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      @Override
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasSurface()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getSurface());
        }
        if (hasBlank()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getBlank());
        }
        if (hasFeature()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getFeature());
        }
        if (hasPosid()) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, getPosid());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme prototype) {
        return new Builder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.newBuilder()
        private Builder() {}
        
        net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme result = new net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme();
        
        @Override
        protected net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme internalGetResult() {
          return result;
        }
        
        @Override
        public Builder clear() {
          result = new net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme();
          return this;
        }
        
        @Override
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDescriptor();
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getDefaultInstanceForType() {
          return net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance();
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme build() {
          if (result != null && !isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");  }
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme returnMe = result;
          result = null;
          return returnMe;
        }
        
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme) {
            return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme other) {
          if (other == net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance()) return this;
          if (other.hasSurface()) {
            setSurface(other.getSurface());
          }
          if (other.hasBlank()) {
            setBlank(other.getBlank());
          }
          if (other.hasFeature()) {
            setFeature(other.getFeature());
          }
          if (other.hasPosid()) {
            setPosid(other.getPosid());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return mergeFrom(input,
            com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
        }
        
        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistry extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setSurface(input.readString());
                break;
              }
              case 18: {
                setBlank(input.readString());
                break;
              }
              case 26: {
                setFeature(input.readString());
                break;
              }
              case 32: {
                setPosid(input.readUInt32());
                break;
              }
            }
          }
        }
        
        
        // required string surface = 1;
        public boolean hasSurface() {
          return result.hasSurface();
        }
        public java.lang.String getSurface() {
          return result.getSurface();
        }
        public Builder setSurface(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasSurface = true;
          result.surface_ = value;
          return this;
        }
        public Builder clearSurface() {
          result.hasSurface = false;
          result.surface_ = "";
          return this;
        }
        
        // optional string blank = 2;
        public boolean hasBlank() {
          return result.hasBlank();
        }
        public java.lang.String getBlank() {
          return result.getBlank();
        }
        public Builder setBlank(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasBlank = true;
          result.blank_ = value;
          return this;
        }
        public Builder clearBlank() {
          result.hasBlank = false;
          result.blank_ = "";
          return this;
        }
        
        // required string feature = 3;
        public boolean hasFeature() {
          return result.hasFeature();
        }
        public java.lang.String getFeature() {
          return result.getFeature();
        }
        public Builder setFeature(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasFeature = true;
          result.feature_ = value;
          return this;
        }
        public Builder clearFeature() {
          result.hasFeature = false;
          result.feature_ = "";
          return this;
        }
        
        // required uint32 posid = 4;
        public boolean hasPosid() {
          return result.hasPosid();
        }
        public int getPosid() {
          return result.getPosid();
        }
        public Builder setPosid(int value) {
          result.hasPosid = true;
          result.posid_ = value;
          return this;
        }
        public Builder clearPosid() {
          result.hasPosid = false;
          result.posid_ = 0;
          return this;
        }
      }
      
      static {
        net.moraleboost.mecab.impl.Messages.getDescriptor();
      }
    }
    
    // repeated .net.moraleboost.mecab.impl.ParsingResponse.Morpheme morpheme = 1;
    public static final int MORPHEME_FIELD_NUMBER = 1;
    private java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> morpheme_ =
      java.util.Collections.emptyList();
    public java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> getMorphemeList() {
      return morpheme_;
    }
    public int getMorphemeCount() { return morpheme_.size(); }
    public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getMorpheme(int index) {
      return morpheme_.get(index);
    }
    
    @Override
    public final boolean isInitialized() {
      for (net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme element : getMorphemeList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme element : getMorphemeList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme element : getMorphemeList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingResponse prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.moraleboost.mecab.impl.Messages.ParsingResponse.newBuilder()
      private Builder() {}
      
      net.moraleboost.mecab.impl.Messages.ParsingResponse result = new net.moraleboost.mecab.impl.Messages.ParsingResponse();
      
      @Override
      protected net.moraleboost.mecab.impl.Messages.ParsingResponse internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.moraleboost.mecab.impl.Messages.ParsingResponse();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingResponse.getDescriptor();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse getDefaultInstanceForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingResponse.getDefaultInstance();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.moraleboost.mecab.impl.Messages.ParsingResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.morpheme_ != java.util.Collections.EMPTY_LIST) {
          result.morpheme_ =
            java.util.Collections.unmodifiableList(result.morpheme_);
        }
        net.moraleboost.mecab.impl.Messages.ParsingResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingResponse) {
          return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingResponse other) {
        if (other == net.moraleboost.mecab.impl.Messages.ParsingResponse.getDefaultInstance()) return this;
        if (!other.morpheme_.isEmpty()) {
          if (result.morpheme_.isEmpty()) {
            result.morpheme_ = new java.util.ArrayList<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme>();
          }
          result.morpheme_.addAll(other.morpheme_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder subBuilder = net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMorpheme(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .net.moraleboost.mecab.impl.ParsingResponse.Morpheme morpheme = 1;
      public java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> getMorphemeList() {
        return java.util.Collections.unmodifiableList(result.morpheme_);
      }
      public int getMorphemeCount() {
        return result.getMorphemeCount();
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getMorpheme(int index) {
        return result.getMorpheme(index);
      }
      public Builder setMorpheme(int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.morpheme_.set(index, value);
        return this;
      }
      public Builder setMorpheme(int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder builderForValue) {
        result.morpheme_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMorpheme(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.morpheme_.isEmpty()) {
          result.morpheme_ = new java.util.ArrayList<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme>();
        }
        result.morpheme_.add(value);
        return this;
      }
      public Builder addMorpheme(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder builderForValue) {
        if (result.morpheme_.isEmpty()) {
          result.morpheme_ = new java.util.ArrayList<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme>();
        }
        result.morpheme_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMorpheme(
          java.lang.Iterable<? extends net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> values) {
        if (result.morpheme_.isEmpty()) {
          result.morpheme_ = new java.util.ArrayList<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme>();
        }
        super.addAll(values, result.morpheme_);
        return this;
      }
      public Builder clearMorpheme() {
        result.morpheme_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.moraleboost.mecab.impl.Messages.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016messages.proto\022\032net.moraleboost.mecab." +
      "impl\"\036\n\016ParsingRequest\022\014\n\004text\030\001 \002(\t\"\245\001\n" +
      "\017ParsingResponse\022F\n\010morpheme\030\001 \003(\01324.net" +
      ".moraleboost.mecab.impl.ParsingResponse." +
      "Morpheme\032J\n\010Morpheme\022\017\n\007surface\030\001 \002(\t\022\r\n" +
      "\005blank\030\002 \001(\t\022\017\n\007feature\030\003 \002(\t\022\r\n\005posid\030\004" +
      " \002(\r";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor,
              new java.lang.String[] { "Text", },
              net.moraleboost.mecab.impl.Messages.ParsingRequest.class,
              net.moraleboost.mecab.impl.Messages.ParsingRequest.Builder.class);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor,
              new java.lang.String[] { "Morpheme", },
              net.moraleboost.mecab.impl.Messages.ParsingResponse.class,
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Builder.class);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor =
            internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor.getNestedTypes().get(0);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor,
              new java.lang.String[] { "Surface", "Blank", "Feature", "Posid", },
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.class,
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
