// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package net.moraleboost.mecab.impl;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParsingRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string text = 1;
    boolean hasText();
    String getText();
  }
  public static final class ParsingRequest extends
      com.google.protobuf.GeneratedMessage
      implements ParsingRequestOrBuilder {
    // Use ParsingRequest.newBuilder() to construct.
    private ParsingRequest(Builder builder) {
      super(builder);
    }
    private ParsingRequest(boolean noInit) {}
    
    private static final ParsingRequest defaultInstance;
    public static ParsingRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParsingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.moraleboost.mecab.impl.Messages.ParsingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable;
      }
      
      // Construct using net.moraleboost.mecab.impl.Messages.ParsingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingRequest.getDescriptor();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest getDefaultInstanceForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingRequest.getDefaultInstance();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest build() {
        net.moraleboost.mecab.impl.Messages.ParsingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.moraleboost.mecab.impl.Messages.ParsingRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.moraleboost.mecab.impl.Messages.ParsingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingRequest buildPartial() {
        net.moraleboost.mecab.impl.Messages.ParsingRequest result = new net.moraleboost.mecab.impl.Messages.ParsingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingRequest) {
          return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingRequest other) {
        if (other == net.moraleboost.mecab.impl.Messages.ParsingRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:net.moraleboost.mecab.impl.ParsingRequest)
    }
    
    static {
      defaultInstance = new ParsingRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.moraleboost.mecab.impl.ParsingRequest)
  }
  
  public interface ParsingResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .net.moraleboost.mecab.impl.ParsingResponse.Morpheme morpheme = 1;
    java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> 
        getMorphemeList();
    net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getMorpheme(int index);
    int getMorphemeCount();
    java.util.List<? extends net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder> 
        getMorphemeOrBuilderList();
    net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder getMorphemeOrBuilder(
        int index);
  }
  public static final class ParsingResponse extends
      com.google.protobuf.GeneratedMessage
      implements ParsingResponseOrBuilder {
    // Use ParsingResponse.newBuilder() to construct.
    private ParsingResponse(Builder builder) {
      super(builder);
    }
    private ParsingResponse(boolean noInit) {}
    
    private static final ParsingResponse defaultInstance;
    public static ParsingResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParsingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable;
    }
    
    public interface MorphemeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string surface = 1;
      boolean hasSurface();
      String getSurface();
      
      // optional string blank = 2;
      boolean hasBlank();
      String getBlank();
      
      // required string feature = 3;
      boolean hasFeature();
      String getFeature();
      
      // required uint32 posid = 4;
      boolean hasPosid();
      int getPosid();
    }
    public static final class Morpheme extends
        com.google.protobuf.GeneratedMessage
        implements MorphemeOrBuilder {
      // Use Morpheme.newBuilder() to construct.
      private Morpheme(Builder builder) {
        super(builder);
      }
      private Morpheme(boolean noInit) {}
      
      private static final Morpheme defaultInstance;
      public static Morpheme getDefaultInstance() {
        return defaultInstance;
      }
      
      public Morpheme getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string surface = 1;
      public static final int SURFACE_FIELD_NUMBER = 1;
      private java.lang.Object surface_;
      public boolean hasSurface() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSurface() {
        java.lang.Object ref = surface_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            surface_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getSurfaceBytes() {
        java.lang.Object ref = surface_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          surface_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string blank = 2;
      public static final int BLANK_FIELD_NUMBER = 2;
      private java.lang.Object blank_;
      public boolean hasBlank() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getBlank() {
        java.lang.Object ref = blank_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            blank_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getBlankBytes() {
        java.lang.Object ref = blank_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          blank_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string feature = 3;
      public static final int FEATURE_FIELD_NUMBER = 3;
      private java.lang.Object feature_;
      public boolean hasFeature() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getFeature() {
        java.lang.Object ref = feature_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            feature_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getFeatureBytes() {
        java.lang.Object ref = feature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          feature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required uint32 posid = 4;
      public static final int POSID_FIELD_NUMBER = 4;
      private int posid_;
      public boolean hasPosid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPosid() {
        return posid_;
      }
      
      private void initFields() {
        surface_ = "";
        blank_ = "";
        feature_ = "";
        posid_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasSurface()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFeature()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPosid()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getSurfaceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getBlankBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getFeatureBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt32(4, posid_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getSurfaceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getBlankBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getFeatureBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, posid_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable;
        }
        
        // Construct using net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          surface_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          blank_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          feature_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          posid_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDescriptor();
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getDefaultInstanceForType() {
          return net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance();
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme build() {
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme buildPartial() {
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme result = new net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.surface_ = surface_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.blank_ = blank_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.feature_ = feature_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.posid_ = posid_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme) {
            return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme other) {
          if (other == net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance()) return this;
          if (other.hasSurface()) {
            setSurface(other.getSurface());
          }
          if (other.hasBlank()) {
            setBlank(other.getBlank());
          }
          if (other.hasFeature()) {
            setFeature(other.getFeature());
          }
          if (other.hasPosid()) {
            setPosid(other.getPosid());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasSurface()) {
            
            return false;
          }
          if (!hasFeature()) {
            
            return false;
          }
          if (!hasPosid()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                surface_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                blank_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                feature_ = input.readBytes();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                posid_ = input.readUInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string surface = 1;
        private java.lang.Object surface_ = "";
        public boolean hasSurface() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getSurface() {
          java.lang.Object ref = surface_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            surface_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setSurface(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          surface_ = value;
          onChanged();
          return this;
        }
        public Builder clearSurface() {
          bitField0_ = (bitField0_ & ~0x00000001);
          surface_ = getDefaultInstance().getSurface();
          onChanged();
          return this;
        }
        void setSurface(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          surface_ = value;
          onChanged();
        }
        
        // optional string blank = 2;
        private java.lang.Object blank_ = "";
        public boolean hasBlank() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getBlank() {
          java.lang.Object ref = blank_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            blank_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setBlank(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          blank_ = value;
          onChanged();
          return this;
        }
        public Builder clearBlank() {
          bitField0_ = (bitField0_ & ~0x00000002);
          blank_ = getDefaultInstance().getBlank();
          onChanged();
          return this;
        }
        void setBlank(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          blank_ = value;
          onChanged();
        }
        
        // required string feature = 3;
        private java.lang.Object feature_ = "";
        public boolean hasFeature() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getFeature() {
          java.lang.Object ref = feature_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            feature_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setFeature(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          feature_ = value;
          onChanged();
          return this;
        }
        public Builder clearFeature() {
          bitField0_ = (bitField0_ & ~0x00000004);
          feature_ = getDefaultInstance().getFeature();
          onChanged();
          return this;
        }
        void setFeature(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          feature_ = value;
          onChanged();
        }
        
        // required uint32 posid = 4;
        private int posid_ ;
        public boolean hasPosid() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public int getPosid() {
          return posid_;
        }
        public Builder setPosid(int value) {
          bitField0_ |= 0x00000008;
          posid_ = value;
          onChanged();
          return this;
        }
        public Builder clearPosid() {
          bitField0_ = (bitField0_ & ~0x00000008);
          posid_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:net.moraleboost.mecab.impl.ParsingResponse.Morpheme)
      }
      
      static {
        defaultInstance = new Morpheme(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:net.moraleboost.mecab.impl.ParsingResponse.Morpheme)
    }
    
    // repeated .net.moraleboost.mecab.impl.ParsingResponse.Morpheme morpheme = 1;
    public static final int MORPHEME_FIELD_NUMBER = 1;
    private java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> morpheme_;
    public java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> getMorphemeList() {
      return morpheme_;
    }
    public java.util.List<? extends net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder> 
        getMorphemeOrBuilderList() {
      return morpheme_;
    }
    public int getMorphemeCount() {
      return morpheme_.size();
    }
    public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getMorpheme(int index) {
      return morpheme_.get(index);
    }
    public net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder getMorphemeOrBuilder(
        int index) {
      return morpheme_.get(index);
    }
    
    private void initFields() {
      morpheme_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMorphemeCount(); i++) {
        if (!getMorpheme(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < morpheme_.size(); i++) {
        output.writeMessage(1, morpheme_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < morpheme_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, morpheme_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.moraleboost.mecab.impl.Messages.ParsingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.moraleboost.mecab.impl.Messages.ParsingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.moraleboost.mecab.impl.Messages.ParsingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moraleboost.mecab.impl.Messages.internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable;
      }
      
      // Construct using net.moraleboost.mecab.impl.Messages.ParsingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMorphemeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (morphemeBuilder_ == null) {
          morpheme_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          morphemeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingResponse.getDescriptor();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse getDefaultInstanceForType() {
        return net.moraleboost.mecab.impl.Messages.ParsingResponse.getDefaultInstance();
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse build() {
        net.moraleboost.mecab.impl.Messages.ParsingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.moraleboost.mecab.impl.Messages.ParsingResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.moraleboost.mecab.impl.Messages.ParsingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.moraleboost.mecab.impl.Messages.ParsingResponse buildPartial() {
        net.moraleboost.mecab.impl.Messages.ParsingResponse result = new net.moraleboost.mecab.impl.Messages.ParsingResponse(this);
        int from_bitField0_ = bitField0_;
        if (morphemeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            morpheme_ = java.util.Collections.unmodifiableList(morpheme_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.morpheme_ = morpheme_;
        } else {
          result.morpheme_ = morphemeBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moraleboost.mecab.impl.Messages.ParsingResponse) {
          return mergeFrom((net.moraleboost.mecab.impl.Messages.ParsingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.moraleboost.mecab.impl.Messages.ParsingResponse other) {
        if (other == net.moraleboost.mecab.impl.Messages.ParsingResponse.getDefaultInstance()) return this;
        if (morphemeBuilder_ == null) {
          if (!other.morpheme_.isEmpty()) {
            if (morpheme_.isEmpty()) {
              morpheme_ = other.morpheme_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMorphemeIsMutable();
              morpheme_.addAll(other.morpheme_);
            }
            onChanged();
          }
        } else {
          if (!other.morpheme_.isEmpty()) {
            if (morphemeBuilder_.isEmpty()) {
              morphemeBuilder_.dispose();
              morphemeBuilder_ = null;
              morpheme_ = other.morpheme_;
              bitField0_ = (bitField0_ & ~0x00000001);
              morphemeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMorphemeFieldBuilder() : null;
            } else {
              morphemeBuilder_.addAllMessages(other.morpheme_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMorphemeCount(); i++) {
          if (!getMorpheme(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder subBuilder = net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMorpheme(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .net.moraleboost.mecab.impl.ParsingResponse.Morpheme morpheme = 1;
      private java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> morpheme_ =
        java.util.Collections.emptyList();
      private void ensureMorphemeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          morpheme_ = new java.util.ArrayList<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme>(morpheme_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder, net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder> morphemeBuilder_;
      
      public java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> getMorphemeList() {
        if (morphemeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(morpheme_);
        } else {
          return morphemeBuilder_.getMessageList();
        }
      }
      public int getMorphemeCount() {
        if (morphemeBuilder_ == null) {
          return morpheme_.size();
        } else {
          return morphemeBuilder_.getCount();
        }
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme getMorpheme(int index) {
        if (morphemeBuilder_ == null) {
          return morpheme_.get(index);
        } else {
          return morphemeBuilder_.getMessage(index);
        }
      }
      public Builder setMorpheme(
          int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme value) {
        if (morphemeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMorphemeIsMutable();
          morpheme_.set(index, value);
          onChanged();
        } else {
          morphemeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMorpheme(
          int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder builderForValue) {
        if (morphemeBuilder_ == null) {
          ensureMorphemeIsMutable();
          morpheme_.set(index, builderForValue.build());
          onChanged();
        } else {
          morphemeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMorpheme(net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme value) {
        if (morphemeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMorphemeIsMutable();
          morpheme_.add(value);
          onChanged();
        } else {
          morphemeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMorpheme(
          int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme value) {
        if (morphemeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMorphemeIsMutable();
          morpheme_.add(index, value);
          onChanged();
        } else {
          morphemeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMorpheme(
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder builderForValue) {
        if (morphemeBuilder_ == null) {
          ensureMorphemeIsMutable();
          morpheme_.add(builderForValue.build());
          onChanged();
        } else {
          morphemeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMorpheme(
          int index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder builderForValue) {
        if (morphemeBuilder_ == null) {
          ensureMorphemeIsMutable();
          morpheme_.add(index, builderForValue.build());
          onChanged();
        } else {
          morphemeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMorpheme(
          java.lang.Iterable<? extends net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme> values) {
        if (morphemeBuilder_ == null) {
          ensureMorphemeIsMutable();
          super.addAll(values, morpheme_);
          onChanged();
        } else {
          morphemeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMorpheme() {
        if (morphemeBuilder_ == null) {
          morpheme_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          morphemeBuilder_.clear();
        }
        return this;
      }
      public Builder removeMorpheme(int index) {
        if (morphemeBuilder_ == null) {
          ensureMorphemeIsMutable();
          morpheme_.remove(index);
          onChanged();
        } else {
          morphemeBuilder_.remove(index);
        }
        return this;
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder getMorphemeBuilder(
          int index) {
        return getMorphemeFieldBuilder().getBuilder(index);
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder getMorphemeOrBuilder(
          int index) {
        if (morphemeBuilder_ == null) {
          return morpheme_.get(index);  } else {
          return morphemeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder> 
           getMorphemeOrBuilderList() {
        if (morphemeBuilder_ != null) {
          return morphemeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(morpheme_);
        }
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder addMorphemeBuilder() {
        return getMorphemeFieldBuilder().addBuilder(
            net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance());
      }
      public net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder addMorphemeBuilder(
          int index) {
        return getMorphemeFieldBuilder().addBuilder(
            index, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.getDefaultInstance());
      }
      public java.util.List<net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder> 
           getMorphemeBuilderList() {
        return getMorphemeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder, net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder> 
          getMorphemeFieldBuilder() {
        if (morphemeBuilder_ == null) {
          morphemeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme, net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder, net.moraleboost.mecab.impl.Messages.ParsingResponse.MorphemeOrBuilder>(
                  morpheme_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          morpheme_ = null;
        }
        return morphemeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:net.moraleboost.mecab.impl.ParsingResponse)
    }
    
    static {
      defaultInstance = new ParsingResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.moraleboost.mecab.impl.ParsingResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\032net.moraleboost.mecab." +
      "impl\"\036\n\016ParsingRequest\022\014\n\004text\030\001 \002(\t\"\245\001\n" +
      "\017ParsingResponse\022F\n\010morpheme\030\001 \003(\01324.net" +
      ".moraleboost.mecab.impl.ParsingResponse." +
      "Morpheme\032J\n\010Morpheme\022\017\n\007surface\030\001 \002(\t\022\r\n" +
      "\005blank\030\002 \001(\t\022\017\n\007feature\030\003 \002(\t\022\r\n\005posid\030\004" +
      " \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_moraleboost_mecab_impl_ParsingRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingRequest_descriptor,
              new java.lang.String[] { "Text", },
              net.moraleboost.mecab.impl.Messages.ParsingRequest.class,
              net.moraleboost.mecab.impl.Messages.ParsingRequest.Builder.class);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor,
              new java.lang.String[] { "Morpheme", },
              net.moraleboost.mecab.impl.Messages.ParsingResponse.class,
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Builder.class);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor =
            internal_static_net_moraleboost_mecab_impl_ParsingResponse_descriptor.getNestedTypes().get(0);
          internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_moraleboost_mecab_impl_ParsingResponse_Morpheme_descriptor,
              new java.lang.String[] { "Surface", "Blank", "Feature", "Posid", },
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.class,
              net.moraleboost.mecab.impl.Messages.ParsingResponse.Morpheme.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
